2022-11-08 11:51:10,667 ERROR: Exception on /user/susan [GET] [in /home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/routes.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/user.html", line 36, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-11-08 11:54:19,637 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-08 11:54:31,446 ERROR: Exception on /user/susan [GET] [in /home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/routes.py", line 96, in user
    return render_template('user.html', user=user, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/templates/user.html", line 36, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-11-11 00:57:12,130 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:51]
2022-11-11 00:57:45,954 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:51]
